version: 2
updates:
- package-ecosystem: bundler
  directory: "/WcaOnRails"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  # https://github.com/thewca/worldcubeassociation.org/pull/3644
  - dependency-name: seedbank
    versions:
    - 0.5.0
- package-ecosystem: npm
  directory: "/WcaOnRails"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  # We plan on migrating to Fomantic anyways, so no need to bother upgrading bootstrap.
  - dependency-name: react-bootstrap
    versions:
    - ">= 1.0.0"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
